repo_url: https://github.com/orgs/estrato-notes/repositories
repo_name: Estrato

site_name: Estrato - Documentação
theme:
  name: material
  logo: assets/logo/logo-white.svg
  favicon: assets/logo/logo-blue.svg

  palette:
    - scheme: default
      primary: indigo
  
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

nav:
  - 'Visão Geral': 'index.md'
  - 'Backlog': 'backlog.md'
  - 'Diagrama de Classes': 'uml-diagram.md'
  - 'Protótipo de Alta Fidelidade': 'prototype.md'